-- 1/  Retrieve all clients who have made a transaction:

SELECT DISTINCT c.name_client
FROM Client c
INNER JOIN Facture f ON c.client_id = f.client_id
INNER JOIN Transactions t ON f.facture_id = t.facture_id;


-- 2/ Calculate the total amount of transactions made by a specific client :

SELECT c.name_client, SUM(t.Amount) AS total_amount
FROM Client c
INNER JOIN Facture f ON c.client_id = f.client_id
INNER JOIN Transactions t ON f.facture_id = t.facture_id
WHERE c.name_client = 'John Doe'
GROUP BY c.name_client;


-- 3/ Retrieve the top 5 products with the highest quantity in stock: 

SELECT p.product_name, p.Quantity
FROM Product p
ORDER BY p.Quantity DESC
LIMIT 5;

-- 4/ Retrieve the list of products with their corresponding providers:

SELECT p.product_name, pr.provider_name
FROM Product p
INNER JOIN Provider pr ON p.provider_id = pr.provider_id;

-- 5/ Calculate the total revenue for each month in the last year:

SELECT EXTRACT(MONTH FROM t.Date) AS month, EXTRACT(YEAR FROM t.Date) AS year, SUM(t.Amount) AS total_revenue
FROM Transactions t
WHERE t.Date >= NOW() - INTERVAL '1 year'
GROUP BY EXTRACT(MONTH FROM t.Date), EXTRACT(YEAR FROM t.Date)
ORDER BY year, month;

--6/ etrieve the total revenue generated by each product:
SELECT c.name_client, SUM(t.Amount) AS total_amount
FROM Client c
JOIN Facture f ON c.client_id = f.client_id
JOIN Transactions t ON f.facture_id = t.facture_id
GROUP BY c.name_client
ORDER BY total_amount DESC
LIMIT 5;

--7/ Retrieve the clients who have made the highest total amount of transactions:

SELECT c.name_client, SUM(t.Amount) AS total_amount
FROM Client c
JOIN Facture f ON c.client_id = f.client_id
JOIN Transactions t ON f.facture_id = t.facture_id
GROUP BY c.name_client
ORDER BY total_amount DESC
LIMIT 5;


--8/ Retrieve the products that have been sold in the highest quantity:
SELECT p.product_name, SUM(fp.Quantity) AS total_quantity_sold
FROM Facture_Product fp
JOIN Facture f ON fp.facture_id = f.facture_id
JOIN Product p ON fp.product_id = p.product_id
WHERE f.Sorti = 1
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 5;


--9/ Retrieve the providers who have supplied products with the highest total revenue:

SELECT pr.provider_name, SUM(fp.Quantity * p.price) AS total_revenue
FROM Facture_Product fp
JOIN Facture f ON fp.facture_id = f.facture_id
JOIN Product p ON fp.product_id = p.product_id
JOIN Provider pr ON p.provider_id = pr.provider_id
WHERE f.Sorti = 1
GROUP BY pr.provider_name
ORDER BY total_revenue DESC
LIMIT 5;

--10/ Retrieve the clients who have made transactions with a specific product:
SELECT c.name_client, p.product_name
FROM Client c
JOIN Facture f ON c.client_id = f.client_id
JOIN Facture_Product fp ON f.facture_id = fp.facture_id
JOIN Product p ON fp.product_id = p.product_id
WHERE p.product_name = 'iPhone'
GROUP BY c.name_client;

